apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-first-api.fullname" . }}-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "my-first-api.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  postgres-db: {{ .Values.postgresql.auth.database | b64enc | quote }}
  database-url: {{ include "my-first-api.databaseUrl" . | b64enc | quote }}
